# Generated by Django 4.1.3 on 2022-11-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_flexaccount_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexaccount',
            name='account_name',
        ),
    ]
