# Generated by Django 4.1.3 on 2022-11-21 15:38

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_flexaccount_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='transaction.flexaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('transfer', 'transfer'), ('withdraw', 'withdraw')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
