# Generated by Django 4.1.3 on 2022-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_transaction_account_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
